{{- if and .Values.rollout.enabled .Values.rollout.analysis.enabled (eq .Values.rollout.strategy "canary") }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "python-app.fullname" . }}-health
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
spec:
  metrics:
    - name: web-health
      provider:
        web:
          url: http://{{ include "python-app.fullname" . }}-svc.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.port }}/health
          jsonPath: "{$.status}"
      successCondition: result == "healthy"
      interval: {{ .Values.rollout.analysis.interval | quote }}
      count: {{ .Values.rollout.analysis.count }}
      failureLimit: {{ .Values.rollout.analysis.failureLimit }}
{{- end }}
