{{- if and .Values.rollout.enabled (eq .Values.rollout.strategy "blueGreen") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-app.fullname" . }}-svc-preview
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: preview
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "python-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if and (eq .Values.service.type "NodePort") .Values.rollout.blueGreen.previewNodePort }}
      nodePort: {{ .Values.rollout.blueGreen.previewNodePort }}
      {{- end }}
{{- end }}
