apiVersion: v2
name: app-go
description: DevOps Info Service — Go application Helm chart
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - go
  - golang
  - devops
  - web
maintainers:
  - name: newspec
    email: newspec@example.com
sources:
  - https://github.com/newspec/DevOps-Core-Course
dependencies:
  - name: common-lib
    version: 0.1.0
    repository: "file://../common-lib"
